export const DELETETODO='DELETTODO'
export const DONETODO='DONETODO'
export const ADDTODO='ADDTODO'
export const EDITTODO='EDITTODO'
export const Filter='Filter'
export const FilteredTodos='FilteredTodods'